version: "3.1"

services:
  avatar-api:
    image: avatarsys/avatar-api
    ports:
#       - "9001:9001"
    command: python3 manage.py runserver 0.0.0.0:9001
    volumes:
       - ./data:/app/data
    depends_on:
      - postgres
    restart: always

  avatar-ui:
    image: avatarsys/avatar-ui
    depends_on:
      - avatar-api
    ports:
      - "80:80"
    restart: always

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=avatar
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
#    ports:
#      - "127.0.0.1:5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data